'\" t
.\"     Title: apti
.\"    Author: Steve Ivanov SEV007
.\" Generator: vim
.\"      Date: 06\ \&November\ \&2017
.\"    Manual: APTI
.\"    Source: APTI 1.0
.\"  Language: English
.\"
.TH "APTI" "8" "06\ \&November\ \&2017" "APTI 1.0" "APTI"
.\" -----------------------------------------------------------------
.\" * Sources repository
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" https://github.com/SEV007/Linux_Scripts
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.TH man 8 "06 Nov 2017" "1.0" "apti man page"
.SH NAME
apti \- install packages through apt 
.SH SYNOPSIS
apti
.SH DESCRIPTION
apti is a shell script for packages installation based on apt.
.SH OPTIONS
The apti does not take any options, just requires package name on user prompt.
.SH SEE ALSO
apt-get(8), aptu(8) 
.SH BUGS
No known bugs.
.SH AUTHOR
SEV007



