'\" t
.\"     Title: aptu
.\"    Author: Steve Ivanov SEV007
.\" Generator: vim
.\"      Date: 06\ \&November\ \&2017
.\"    Manual: APTU
.\"    Source: APTU 1.0
.\"  Language: English
.\"
.TH "APTU" "8" "06\ \&November\ \&2017" "APTU 1.0" "APTU"
.\" -----------------------------------------------------------------
.\" * Sources repository
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" https://github.com/SEV007/Linux_Scripts
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.TH man 8 "06 Nov 2017" "1.0" "aptu man page"
.SH NAME
aptu \- update apt sources, upgrade system packages and clear unnecessary files 
.SH SYNOPSIS
aptu
.SH DESCRIPTION
aptu is a shell script for system update based on apt.
.SH OPTIONS
The aptu does not take any options.
.SH SEE ALSO
apt-get(8), apti(8) 
.SH BUGS
No known bugs.
.SH AUTHOR
SEV007



